apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: command-demo-container
    image: busybox:1.28.4
    #command: ["printenv"]
    #args: ["HOSTNAME", "KUBERNETES_PORT"]
    command: 
     - sleep
     - "3600"
  restartPolicy: Always