apiVersion: v1
kind: Service
metadata:
    name: myapp-clusterip
spec:
    type: ClusterIP
    ports:
      - port: 80
        targetPort: 80
        #nodePort: 30004
    selector:
          app: myapp    # label of the pod
                