apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: myapp-replicaset
    labels: 
         tier: front-end
         app: nginx
spec:
    selector: 
        matchLabels:
            app: myapp
    replicas: 2
    template:
        metadata:
            name: nginx-2
            labels:
              app: myapp
        spec:
            containers:
            - name: nginx
              image: nginx
                