apiVersion: v1
kind: Pod
metadata:
  name: students-api
  labels:
    app: students-api
spec:
  containers:
  - name: students-express-server
    image: dockerrajmanda/students-express-server:latest  
    ports:
    - containerPort: 3000  
  hostNetwork: true
  dnsPolicy: "None" 
  dnsConfig:
   nameservers:
    - 8.8.8.8
  restartPolicy: Never
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "com.raj.studentsapi"
    - "com.raj.studentsapiserver"  
    
