apiVersion: v1
kind: Service
metadata:
    name: students-api-service 
    labels:
        name: students-api-service
spec:
    type: ClusterIP
    ports:
      - port: 3000
        targetPort: 3000
    selector:
          app: students-api    