apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: students-app-deployment
  name: students-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: students-app-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: students-app-deployment
    spec:
      containers:
      - image: dockerrajmanda/students-angular-app:v4
        name: students-angular-app
        imagePullPolicy: Always
        ports:
        - containerPort: 4200 
        resources: {}
      - image: dockerrajmanda/students-express-server:v1
        name: students-express-server
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      hostNetwork: true
      dnsPolicy: "None" 
      dnsConfig:
       nameservers:
        - 8.8.8.8          
status: {}

