apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: students-api-deployment
  name: students-api-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30004
  selector:
    app: students-api-deployment
  type: NodePort   
status:
  loadBalancer: {}