apiVersion: v1
kind: Service
metadata:
  name: students-api-service
  labels:
    app: students-api-service
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: students-api-deployment
  type: ClusterIP
status:
  loadBalancer: {}
