apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: students-api-deployment
  name: students-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: students-api-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: students-api-deployment
    spec:
      containers:
      - image: dockerrajmanda/students-express-server:v1
        name: students-express-server
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources: {}
      hostNetwork: true
      dnsPolicy: "None"  
      dnsConfig:
        nameservers:
         - 8.8.8.8  
status: {}
