apiVersion: v1
kind: Service
metadata:
  name: students-app-service
  labels:
    app: students-app-deployment
spec:
  ports:
  - port: 4200
    protocol: TCP
    targetPort: 4200
    nodePort: 30005
  selector:
    app: students-app-deployment
  type: NodePort
status:
  loadBalancer: {}
