apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: host-ingress
spec:
  rules:
  - host: "studentsapi.com"
    http:
      paths:
      - backend:
          serviceName: students-api-service
          servicePort: 3000
  - host: "studentsapp.com"
    http:
      paths:
      - backend:
          serviceName: students-app-service
          servicePort: 80
