apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment-result-app
    labels: 
         name: deployment-result-app
         app: demo-voting-app
spec:
    selector: 
        matchLabels:
         name: result-app-pod
         app: demo-result-app
    replicas: 1
    template:
      metadata:
        name: result-app-pod
        labels:
          name: result-app-pod
          app: demo-result-app
      spec:
        containers:
        - name: result-app
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80 
                