apiVersion: v1
kind: Service
metadata:
    name: db
    labels:
        name: postgres-Service
        app: demo-voting-app
spec:
    type: ClusterIP
    ports:
      - port: 5432 
        targetPort: 5432
    selector:                     # copy labels of the postgres-pod
      name: postgres-pod
      app: demo-voting-app  